/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.svelte'],
  theme: {
    extend: {
      colors: {
        'background-primary': 'var(--background-primary)',
        'background-primary-rgb:': 'var(--background-primary-rgb)',
        'background-primary-alt': 'var(--background-primary-alt)',
        'background-secondary': 'var(--background-secondary)',
        'background-secondary-alt': 'var(--background-secondary-alt)',
        'background-modifier-border': 'var(--background-modifier-border)',
        'background-modifier-form-field': 'var(--background-modifier-form-field)',
        'background-modifier-form-field-highlighted': 'var(--background-modifier-form-field-highlighted)',
        'background-modifier-box-shadow': 'var(--background-modifier-box-shadow)',
        'background-modifier-success': 'var(--background-modifier-success)',
        'background-modifier-success-rgb': 'var(--background-modifier-success-rgb)',
        'background-modifier-error': 'var(--background-modifier-error)',
        'background-modifier-error-rgb': 'var(--background-modifier-error-rgb)',
        'background-modifier-error-hover': 'var(--background-modifier-error-hover)',
        'background-modifier-cover': 'var(--background-modifier-cover)',
        'text-accent': 'var(--text-accent)',
        'text-accent-hover': 'var(--text-accent-hover)',
        'text-normal': 'var(--text-normal)',
        'text-muted': 'var(--text-muted)',
        'text-muted-rgb': 'var(--text-muted-rgb)',
        'text-faint': 'var(--text-faint)',
        'text-error': 'var(--text-error)',
        'text-error-hover': 'var(--text-error-hover)',
        'text-highlight-bg': 'var(--text-highlight-bg)',
        'text-highlight-bg-active': 'var(--text-highlight-bg-active)',
        'text-selection': 'var(--text-selection)',
        'text-on-accent': 'var(--text-on-accent)',
        'interactive-normal': 'var(--interactive-normal)',
        'interactive-hover': 'var(--interactive-hover)',
        'interactive-accent': 'var(--interactive-accent)',
        'interactive-accent-rgb': 'var(--interactive-accent-rgb)',
        'interactive-accent-hover': 'var(--interactive-accent-hover)',
        'interactive-success': 'var(--interactive-success)',
        'scrollbar-active-thumb-bg': 'var(--scrollbar-active-thumb-bg)',
        'scrollbar-bg': 'var(--scrollbar-bg)',
        'scrollbar-thumb-bg': 'var(--scrollbar-thumb-bg)',
        'highlight-mix-blend-mode': 'var(--highlight-mix-blend-mode)',
      },
    },
  },
  plugins: [],
};
